config/routes.rb
Rails.application.routes.draw do
  devise_for :controllers
  devise_for :users

  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  resources :dogs do
    resources :bookings, only: [:new, :create, :destroy]
    resources :reviews, only: [:new, :create, :destroy]
  end

  get "users/:id", to: "user_profiles#index", as: :user_profile
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :dog

  validates :date, presence: true
end

app/models/controller.rb
class Controller < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/dog.rb
class Dog < ApplicationRecord
  include PgSearch::Model
  pg_search_scope :global_search,
  against: [ :name, :user_id],
  associated_against: {
    user: [ :first_name, :last_name ]
  },
  using: {
    tsearch: { prefix: true }
  }
  has_one_attached :photo
  belongs_to :user
  has_many :bookings, dependent: :destroy
  has_many :reviews, dependent: :destroy
  validates :name, presence: true
  validates :description, presence: true
  validates :address, presence: true

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :dog
end

app/models/user.rb
class User < ApplicationRecord
  has_one_attached :photo
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :dogs, dependent: :destroy
  has_many :bookings, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :photo])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :photo])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def new
    @dog = Dog.find(params[:dog_id])
    @dog.user = current_user
    @booking = Booking.new
  end

  def create
    @dog = Dog.find(params[:dog_id])
    @booking = Booking.new(booking_params)
    @booking.dog = @dog
    @booking.user = current_user
    if @booking.save
      redirect_to dog_path(@dog)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @booking = Booking.find(params[:id])
    @booking.destroy
    redirect_to dog_path(@bookmark.dog), status: :see_other
  end

  private

  def booking_params
    params.require(:booking).permit(:date, :user_id, :dog_id)
  end
end

app/controllers/dogs_controller.rb
class DogsController < ApplicationController
  def index
    @dogs = Dog.all
    if params[:query].present?
      @dogs = @dogs.global_search(params[:query])

    end
  end

  def show
    @dog = Dog.find(params[:id])
    @marker =
      if @dog.latitude && @dog.longitude
        {
          lat: @dog.latitude,
          lng: @dog.longitude,
          info_window_html: render_to_string(partial: "info_window", locals: {dog: @dog}),
          marker_html: render_to_string(partial: "marker")
        }
      end
  end

  def new
    @dog = Dog.new
  end

  def create
    @dog = Dog.new(dog_params)
    @dog.user = current_user

    if @dog.save
      redirect_to dog_path(@dog)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @dog = Dog.find(params[:id])
  end

  def update
    @dog = Dog.find(params[:id])
    if @dog.update(dog_params)
      redirect_to dog_path(@dog)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @dog = Dog.find(params[:id])
    @dog.destroy
    redirect_to dogs_path, status: :see_other
  end

  private

  def dog_params
    params.require(:dog).permit(:name, :description, :address,:photo, :user_id, )
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home
  def home
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @dog = Dog.find(params[:dog_id])
    @dog.user = current_user
    @review = Review.new
  end

  def create
    @dog = Dog.find(params[:dog_id])
    @review = Review.new(review_params)
    @review.dog = @dog
    @review.user = current_user
    if @review.save
      redirect_to dog_path(@dog)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy
    redirect_to dog_path(@review.dog), status: :see_other
  end

  private

  def review_params
    params.require(:review).permit(:rating, :comment, :user_id, :dog_id)
  end
end

app/controllers/user_profiles_controller.rb
class UserProfilesController < ApplicationController
  def index
    @user = current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/new.html.erb
  <h1>Choose your date</h1>


<div class="container_book">
  <%= simple_form_for [@user, @dog, @booking] do |f| %>
    <%= f.input :date,
        as: :string,
        input_html: { data: { controller: "datepicker" } } %>
    <%= f.submit "Book", class: "btn" %> |
    <%= link_to "Back", dog_path(@dog), class: "btn-back"%>

  <% end %>
</div>

app/views/dogs/_info_window.html.erb
<h4><%= dog.name %></h4>
<p><%= dog.address %></p>

app/views/dogs/_marker.html.erb
<%= image_tag "marker2222.png", height: 50, width: 50, alt: "Logo" %>

app/views/dogs/edit.html.erb
<div class="container">

  <h1>Edit Dog Profile</h1>

  <%= simple_form_for [@user, @dog] do |f| %>
  <%= f.input :name, input_html: { maxlength: 20 }, placeholder: "Maximum 20 characters" %>
  <%= f.input :address %>
  <%= f.input :description, input_html: { maxlength: 100 }, placeholder: "Maximum 100 characters" %>
  <%= f.input :photo, as: :file %>
  <%= f.submit class:'btn' %> |
  <%= link_to 'Show', @dog, class: 'btn' %> |
  <%= link_to 'Back', dogs_path, class: 'btn' %>
  <% end %>


</div>

app/views/dogs/index.html.erb
<div class="page_box">

<div class="span">
<h1>Discover our cute dogs</h1>

 <div class="row justify-content-center">

  <div class="">
    <%= form_with url: dogs_path, method: :get, class: "subscription-form" do %>
       <%= text_field_tag :query,
            params[:query],
            class: "rounded-input",
            placeholder: "Find a dog"
        %>

    <div class=>
      <%= submit_tag "Search", name: "", class: "embedded-button " %>
    </div>
    <% end %>
  </div>
</div>



<div class="button">
<%= link_to "Add dog", new_dog_path(@dog), class: 'btn' %>
</div>
</div>
<div class="card-dogs">
  <% if @dogs.any? %>
    <% @dogs.each do |dog| %>
      <%= link_to dog_path(dog) do %>
        <div class="card-dog">
          <% if dog.photo.attached? %>
            <%= cl_image_tag dog.photo.key, height: 200, width: 200, crop: :fill %>
          <% else %>
            <%= image_tag "defaultimage.png" , height: 200, width: 200, crop: :fill %>
          <% end %>
          <div class="card-dog-infos">
            <div class="btn-name">
              <h4> <%= dog.name %> </h4>
            </div>
          </div>
        </div>
      <% end %>
    <% end %>
  <% else %>
    <em>Sorry, no dogs found.</em>
  <% end %>
</div>



</div>

app/views/dogs/new.html.erb
<h1>Add a dog</h1>
<div class="container_newdog">
  <%= simple_form_for [@user, @dog] do |f| %>
  <%= f.input :name, input_html: { maxlength: 20 }, placeholder: "Maximum 20 characters" %>
  <%= f.input :address,
  input_html: {data: {address_autocomplete_target: "address"}, class: 'd-none'},
  wrapper_html: {data: {controller: "address-autocomplete", address_autocomplete_api_key_value: ENV["MAPBOX_API_KEY"]}} %>
  <%= f.input :description, input_html: { maxlength: 100 }, placeholder: "Maximum 100 characters" %>
  <%= f.input :photo, as: :file %>
  <%= f.submit "Add dog profile", class:'btn' %> |
  <%= link_to "Back", dogs_path, class: 'btn' %>
  <% end %>
</div>

app/views/dogs/show.html.erb
<div class="container">

  <div class="one-dog">
    <div class="ph-btn">
                <% if @dog.photo.attached?  %>
                  <%= cl_image_tag @dog.photo.key , alt: 'dog' %>
                <% else %>
                  <%= image_tag "defaultimage.png",  alt: 'dog' %>
              <% end %>

            <div id="dog-buttons">
              <% if current_user.id != @dog.user_id %>
                <%= link_to "Book a walk", new_dog_booking_path(@dog), class: 'btn' %>
              <% end %>

              <% if @dog.user_id == current_user.id %>
                <%= link_to "Edit", edit_dog_path(@dog), class: 'btn' %>
                <%= link_to "Delete",
                dog_path(@dog), class: 'btn',
                data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %>
              <% end %>

              <% if @dog.bookings.where(user_id: current_user.id).exists? && !@dog.reviews.exists?(user_id: current_user.id) %>
                <%= link_to "Rate", new_dog_review_path(@dog), class: 'btn' %>
              <% end %>
            </div>
    </div>

  <div class="one-dog-infos">
            <p><h1><%= @dog.name %></h1></p>
            <p><h5>Address: </h5> <%= @dog.address %></p>
            <p><h5>Description: </h5> <%= @dog.description %></p>
            <p><h5>Owner: </h5> <%= @dog.user.first_name %></p>
  </div>

  </div>
            <%= link_to "Back to all dogs", dogs_path(@dog), class: "btn btn-back"%>

  <div class="map">
          <div style="width: 100%; height: 300px;"
            data-controller="map"
            data-map-marker-value="<%= @marker.to_json %>"
            data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
    </div>
  </div>

    <div class="div-rev">
      <% if current_user && @dog.reviews.exists?(user_id: current_user.id) %>
    <h4>Reviews</h4>
    <% review = @dog.reviews.find_by(user_id: current_user.id) %>
    <p id="rating-text">
      <%= review.rating %> <i class="fa-solid fa-star"></i>
      <%= review.comment %> by <%= review.user.first_name %> created at <%= review.created_at.strftime("%Y-%m-%d") %>
    </p>
  <% elsif @dog.reviews.present? %>
    <h4>Reviews</h4>
    <% @dog.reviews.each do |review| %>
      <p id="rating-text">
        <%= review.rating %> <i class="fa-solid fa-star"></i>
        <%= review.comment %> by <%= review.user.first_name %> created at <%= review.created_at.strftime("%Y-%m-%d") %>
      </p>
    <% end %>
  <% else %>
    <h4>No reviews yet...</h4>
  <% end %>
    </div>

    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Woofs4U</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
    <link rel="stylesheet" href="https://api.mapbox.com/mapbox-gl-js/plugins/mapbox-gl-geocoder/v5.0.0/mapbox-gl-geocoder.css" type="text/css">
  </head>

  <body>
    <%= render "shared/navbar" %>
    <%= yield %>
    <%= render "shared/flashes" %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="container_home">
    <div class = "image">
    <%= link_to dogs_path do %>
    <%= image_tag "1.png" , alt: 'logo', class: "card-logo" %>
    <% end %>
    </div>
  <div class="home_text">
    <h3 class="h3">Click on the puppy to book a walk with our fluffy friends</h3>
  </div>
  <div>
    <%= link_to "I'm feeling lucky", "https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.pinterest.com%2Fpin%2F722616702707775365%2F&psig=AOvVaw2upnC4-3m9AiFtHLJyqsRr&ust=1700924234119000&source=images&cd=vfe&opi=89978449&ved=0CBEQjRxqFwoTCMD87dfy3IIDFQAAAAAdAAAAABAF", class: "easter" %>
  </div>
</div>

app/views/pages/show.html.erb
<h2><%= @dog.name %></h2>
<p><%= @dog.description %></p>
<p><%= @dog.address %></p>

  <%= link_to "New dog", new_dog_path(@list), class: 'btn btn-primary' %>
  <%= link_to "Back", dogs_path, class: 'btn btn-primary' %> |
  <%= link_to "Delete",
    dog_path(@dog), class: 'btn btn-primary',
    data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}%>

app/views/reviews/new.html.erb
<h1>Review your experience</h1>
<div class="container_rating">
  <%= simple_form_for [@dog, @review] do |f| %>
  <%= f.input :rating, as: :select, collection: 1..5 %>
  <%= f.input :comment %>
  <%= f.submit "Review", class: 'btn' %>
  <%= link_to "Back", dog_path(@dog), class: 'btn' %>
  <% end %>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to "/", class: "navbar-brand" do %>
      <%= image_tag "woof4ulogo.png" %>
    <% end %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">

          <li class="nav-item dropdown">
          <div class="avatar-info">
          <div class="name_user">
            <h5><%= current_user.first_name %> <%= current_user.last_name %></h5>
          </div>

            <% if current_user.photo.attached? %>
            <%= cl_image_tag current_user.photo.key, class: "avatar", alt: "dropdown menu" %>
            <% else %>
            <%= image_tag "defaultimage.png" , class: "avatar", alt: "dropdown menu" %>
            <% end %>
            </div>
          </a>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Edit profile", edit_user_registration_path, class: "dropdown-item" %>
              <%= link_to "My bookings",user_profile_path(current_user) , class: "dropdown-item" %>
              <%= link_to "All dogs",dogs_path, class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="btn">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/user_profiles/index.html.erb
<div class="box">

  <h1>My Bookings</h1>
  <% current_user.bookings.each do |booking| %>
      <%= link_to dog_path(booking.dog) do %>
    <div class="card-box">
      <div class="text">
        <h5><%= booking.dog.name %></h5>
        <br>
        <h6 class="new"><strong>Date: </strong><%= booking.date %></h6>
        <br>
        <h6 class="new"><strong>Pick up & Drop off: </strong><%= booking.dog.address %></h6>
      </div>
        <div id="img-dog">
        <% if booking.dog.photo.attached? %>
        <%= cl_image_tag booking.dog.photo.key, crop: :fill %>
        <% else %>
        <%= image_tag "defaultimage.png" , crop: :fill%>
        <% end %>
        </div>
    </div>
        <% end %>

      <% end %>

</div>